services:
  postgres:
    container_name: wagering-db
    image: postgres:18.4
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    network_mode: host

  gateway:
    build:
      args:
        - GATEWAY_PORT=${GATEWAY_PORT}
      context: .
      dockerfile: docker/gateway.Dockerfile
    network_mode: host

  wagering-worker:
    build:
      context: .
      dockerfile: docker/wagering-worker.Dockerfile
    deploy:
      replicas: 5
